### ISSUE TITLE
Question about polarization in your force field.

### ISSUE THREAD

**Issue by Ternity** [Yangxinsix/painn-sli#1]
Dear Author:
    I have read your paper published in the [Chem. Sci.](https://pubs.rsc.org/en/content/articlehtml/2023/sc/d2sc06696c) and I am very interested in your work.
    I noticed that you mentioned that the MLFF used is '`polarizable` atom interaction neural network (PaiNN) model'. And my question is: does a `polarizable force field` mean it can predict the distribution of charges? If possible, is this force field can be used to implement the constant potential method in the field of electrochemistry?
    Thank you! Looking forward to your reply.

**Comment by Yangxinsix** [comment]
Hi Ternity!
Regarding your question, it is possible to predict atomic charges if you are training on charges. You can simply output two variables in the `readout` block in the model, one for energy and one for charge. But the problem is that this method does not guarantee that the total charge is conserved (the predicted total charge may be different from the real one).

To make sure the total charge conservation, you can resort to some other methods like charge equilibration scheme in 4-th BPNNP or spookynet. It will better fit the scenario in electrochemistry.

**Comment by Ternity** [comment]
Hi Yangxinsix!
Thank you very much for your reply. Your answer about the relationship between charge prediction and the constant potential model is very enlightening. This information will be very useful.
Thanks again for your time and expertise!
